using System;
using System.Collections.Generic;
using System.IO;
using Mdr.Revit.Core.Models;

namespace Mdr.Revit.Addin.UI
{
    public sealed class ExcelSyncWindowViewModel
    {
        private readonly List<string> _scheduleNames = new List<string>();
        private readonly List<ExcelSyncMappingItem> _columnMappings = new List<ExcelSyncMappingItem>();
        private bool _filePathAutoGenerated;

        public ExcelSyncWindowViewModel()
        {
            EnsureDefaultMappings();
        }

        public IReadOnlyList<string> ScheduleNames => _scheduleNames;

        public IReadOnlyList<ExcelSyncMappingItem> ColumnMappings => _columnMappings;

        public IReadOnlyList<string> Directions { get; } = new[]
        {
            GoogleSyncDirections.Export,
            GoogleSyncDirections.Import,
        };

        public string Direction { get; set; } = GoogleSyncDirections.Export;

        public string SelectedScheduleName { get; set; } = string.Empty;

        public string FilePath { get; set; } = string.Empty;

        public string WorksheetName { get; set; } = string.Empty;

        public string AnchorColumn { get; set; } = "MDR_UNIQUE_ID";

        public string DefaultDirectory { get; private set; } = string.Empty;

        public bool PreviewOnly { get; set; }

        public void SetDefaults(string defaultDirectory, string worksheetName, string anchorColumn)
        {
            if (!string.IsNullOrWhiteSpace(defaultDirectory))
            {
                DefaultDirectory = Environment.ExpandEnvironmentVariables(defaultDirectory.Replace("/", "\\"));
            }

            if (!string.IsNullOrWhiteSpace(worksheetName))
            {
                WorksheetName = worksheetName.Trim();
            }

            if (!string.IsNullOrWhiteSpace(anchorColumn))
            {
                AnchorColumn = anchorColumn.Trim();
            }

            EnsureDefaultFilePath();
        }

        public void SetScheduleNames(IReadOnlyList<string> names)
        {
            _scheduleNames.Clear();
            if (names != null)
            {
                for (int i = 0; i < names.Count; i++)
                {
                    string value = (names[i] ?? string.Empty).Trim();
                    if (string.IsNullOrWhiteSpace(value))
                    {
                        continue;
                    }

                    if (_scheduleNames.Exists(x => string.Equals(x, value, StringComparison.OrdinalIgnoreCase)))
                    {
                        continue;
                    }

                    _scheduleNames.Add(value);
                }
            }

            if (_scheduleNames.Count == 0)
            {
                SelectedScheduleName = string.Empty;
                return;
            }

            bool hasCurrentSelection = _scheduleNames.Exists(x =>
                string.Equals(x, SelectedScheduleName, StringComparison.OrdinalIgnoreCase));
            if (!hasCurrentSelection)
            {
                SelectedScheduleName = _scheduleNames[0];
            }

            if (string.IsNullOrWhiteSpace(WorksheetName))
            {
                WorksheetName = SelectedScheduleName;
            }

            EnsureDefaultFilePath();
        }

        public void ApplySelectedScheduleDefaults()
        {
            if (string.IsNullOrWhiteSpace(WorksheetName))
            {
                WorksheetName = string.IsNullOrWhiteSpace(SelectedScheduleName)
                    ? "Sheet1"
                    : SelectedScheduleName.Trim();
            }

            EnsureDefaultFilePath();
        }

        public void ApplyProtectedColumns(IReadOnlyList<string> protectedColumns)
        {
            if (protectedColumns == null || protectedColumns.Count == 0)
            {
                return;
            }

            for (int i = 0; i < protectedColumns.Count; i++)
            {
                string name = (protectedColumns[i] ?? string.Empty).Trim();
                if (string.IsNullOrWhiteSpace(name))
                {
                    continue;
                }

                ExcelSyncMappingItem? existing = _columnMappings.Find(x =>
                    string.Equals(x.ExcelColumn, name, StringComparison.OrdinalIgnoreCase));
                if (existing == null)
                {
                    _columnMappings.Add(new ExcelSyncMappingItem
                    {
                        ExcelColumn = name,
                        RevitParameter = name,
                        IsEditable = false,
                    });
                    continue;
                }

                existing.IsEditable = false;
                if (string.IsNullOrWhiteSpace(existing.RevitParameter))
                {
                    existing.RevitParameter = name;
                }
            }
        }

        public void SetColumnMappings(IReadOnlyList<GoogleSheetColumnMapping> mappings)
        {
            _columnMappings.Clear();

            HashSet<string> seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            if (mappings != null)
            {
                for (int i = 0; i < mappings.Count; i++)
                {
                    GoogleSheetColumnMapping item = mappings[i];
                    if (item == null)
                    {
                        continue;
                    }

                    string excelColumn = (item.SheetColumn ?? string.Empty).Trim();
                    string revitParameter = (item.RevitParameter ?? string.Empty).Trim();
                    if (string.IsNullOrWhiteSpace(excelColumn) || string.IsNullOrWhiteSpace(revitParameter))
                    {
                        continue;
                    }

                    if (!seen.Add(excelColumn))
                    {
                        continue;
                    }

                    _columnMappings.Add(new ExcelSyncMappingItem
                    {
                        ExcelColumn = excelColumn,
                        RevitParameter = revitParameter,
                        IsEditable = item.IsEditable,
                    });
                }
            }

            if (_columnMappings.Count == 0)
            {
                EnsureDefaultMappings();
            }
        }

        public ExcelSyncFromAppRequest BuildRequest()
        {
            ExcelSyncFromAppRequest request = new ExcelSyncFromAppRequest
            {
                Direction = NormalizeDirection(Direction),
                ScheduleName = (SelectedScheduleName ?? string.Empty).Trim(),
                FilePath = (FilePath ?? string.Empty).Trim(),
                WorksheetName = (WorksheetName ?? string.Empty).Trim(),
                AnchorColumn = string.IsNullOrWhiteSpace(AnchorColumn) ? "MDR_UNIQUE_ID" : AnchorColumn.Trim(),
                PreviewOnly = PreviewOnly,
            };

            for (int i = 0; i < _columnMappings.Count; i++)
            {
                ExcelSyncMappingItem row = _columnMappings[i];
                if (string.IsNullOrWhiteSpace(row.ExcelColumn) || string.IsNullOrWhiteSpace(row.RevitParameter))
                {
                    continue;
                }

                request.ColumnMappings.Add(new GoogleSheetColumnMapping
                {
                    SheetColumn = row.ExcelColumn.Trim(),
                    RevitParameter = row.RevitParameter.Trim(),
                    IsEditable = row.IsEditable,
                });
            }

            return request;
        }

        public void EnsureDefaultMappings()
        {
            if (_columnMappings.Count > 0)
            {
                return;
            }

            _columnMappings.Add(new ExcelSyncMappingItem
            {
                ExcelColumn = "MDR_UNIQUE_ID",
                RevitParameter = "MDR_UNIQUE_ID",
                IsEditable = false,
            });

            _columnMappings.Add(new ExcelSyncMappingItem
            {
                ExcelColumn = "MDR_ELEMENT_ID",
                RevitParameter = "MDR_ELEMENT_ID",
                IsEditable = false,
            });
        }

        private void EnsureDefaultFilePath()
        {
            if ((!string.IsNullOrWhiteSpace(FilePath) && !_filePathAutoGenerated) ||
                string.IsNullOrWhiteSpace(DefaultDirectory))
            {
                return;
            }

            string name = string.IsNullOrWhiteSpace(SelectedScheduleName)
                ? "revit-schedule"
                : SelectedScheduleName.Trim();
            FilePath = Path.Combine(DefaultDirectory, SanitizeFileName(name) + ".xlsx");
            _filePathAutoGenerated = true;
        }

        private static string NormalizeDirection(string value)
        {
            if (string.Equals(value, GoogleSyncDirections.Import, StringComparison.OrdinalIgnoreCase))
            {
                return GoogleSyncDirections.Import;
            }

            return GoogleSyncDirections.Export;
        }

        private static string SanitizeFileName(string value)
        {
            string normalized = string.IsNullOrWhiteSpace(value) ? "revit-schedule" : value.Trim();
            char[] invalid = Path.GetInvalidFileNameChars();
            for (int i = 0; i < invalid.Length; i++)
            {
                normalized = normalized.Replace(invalid[i], '_');
            }

            return normalized;
        }
    }

    public sealed class ExcelSyncMappingItem
    {
        public string ExcelColumn { get; set; } = string.Empty;

        public string RevitParameter { get; set; } = string.Empty;

        public bool IsEditable { get; set; } = true;
    }
}
